### ISSUE TITLE
can i use it to clear all quotes ? 

### ISSUE THREAD

**Issue by jihadbek** [DominicWatts/QuoteCleaner#3]
Hi,
thanks it seams to work great , but i have a non valid quotes ( i think ) which did not get deleted from database with this extension even it is a year old .. a suggestion to add option to clear all quotes regardless of date/time

**Comment by DominicWatts** [comment]
You would need to create a brand new method called clearAllQuotes and take out the query filter

Delete from select will work the same way

Feel free to create a pull request

**Comment by jihadbek** [comment]
i dont have enough knowledge to do that , maybe if you had some free time
to add it ..
Does truncating "quote" and "quote_*" tables would be a safe way to do that
as well ?
‫في الجمعة، 31 يوليو 2020 في 2:05 ص تمت كتابة ما يلي بواسطة ‪DominicWatts‬‏
<‪notifications@github.com‬‏>:‬

**Comment by DominicWatts** [comment]
Truncating quote tables would work
